# Generated by Django 3.2.20 on 2023-07-28 11:05

import cloudinary.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('featured_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('description', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
                ('likes', models.ManyToManyField(blank=True, related_name='event_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=80)),
                ('useremail', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='eventbooking.event')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('timeblock', models.CharField(choices=[('8:00 AM - 12:00 PM', '8:00 AM - 12:00 PM'), ('14:00 AM - 18:00 PM', '14:00 AM - 18:00 PM'), ('20:00 AM - 00:00 AM', '20:00 AM - 00:00 AM')], max_length=50, null=True)),
                ('theme', models.TextField(max_length=200)),
                ('guests', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(50)])),
                ('menu', models.CharField(choices=[('Italien', 'italien'), ('chinese', 'chinese'), ('oriental', 'oriental'), ('indien', 'indien'), ('snacks', 'snacks')], max_length=100, null=True)),
                ('cake', models.CharField(max_length=20, null=True)),
                ('drinks', models.CharField(choices=[('juices', 'juices'), ('shakes', 'shakes'), ('smoothies', 'smoothies'), ('cocktails', 'cocktails'), ('fizzy drinks', 'fizzy drinks')], max_length=100, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_bookings', to='eventbooking.event')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
