# Generated by Django 3.2.20 on 2023-07-10 14:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('eventbooking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 7, 10, 14, 0, 42, 992228, tzinfo=utc)),
        ),
    ]
