# Generated by Django 3.2.20 on 2023-07-19 20:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('eventbooking', '0007_auto_20230719_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 7, 19, 20, 53, 19, 571369, tzinfo=utc)),
        ),
    ]
