# Generated by Django 3.2.20 on 2023-07-21 22:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('eventbooking', '0010_auto_20230721_0922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='event',
        ),
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 7, 21, 22, 14, 39, 187148, tzinfo=utc)),
        ),
    ]
