# Generated by Django 3.2.20 on 2023-07-23 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventbooking', '0013_auto_20230723_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.TimeField(choices=[(0, '08:00 AM– 12:00 PM'), (1, '14:00 AM– 18:00 PM'), (0, '20:00 AM– 00:00 PM')]),
        ),
    ]
