# Generated by Django 3.2.20 on 2023-07-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventbooking', '0015_auto_20230725_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='timeblock',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
