# Generated by Django 3.2.20 on 2023-07-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventbooking', '0016_alter_booking_timeblock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(),
            preserve_default=False,
        ),
    ]
