# Generated by Django 3.2.20 on 2023-07-26 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventbooking', '0018_alter_booking_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='useremail',
        ),
        migrations.AlterField(
            model_name='booking',
            name='drinks',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='menu',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='theme',
            field=models.TextField(max_length=200),
        ),
    ]
