# Generated by Django 3.2.20 on 2023-07-27 07:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventbooking', '0019_auto_20230726_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cake',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='drinks',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='guests',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='menu',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
