# Generated by Django 3.2.20 on 2023-07-27 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventbooking', '0020_auto_20230727_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='drinks',
            field=models.CharField(choices=[('juices', 'juices'), ('shakes', 'shakes'), ('smoothies', 'smoothies'), ('cocktails', 'cocktails'), ('fizzy drinks', 'fizzy drinks')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='menu',
            field=models.CharField(choices=[('Italien', 'italien'), ('chinese', 'chinese'), ('oriental', 'oriental'), ('indien', 'indien'), ('snacks', 'snacks')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='timeblock',
            field=models.CharField(choices=[('8:00 AM - 12:00 PM', '8:00 AM - 12:00 PM'), ('14:00 AM - 18:00 PM', '14:00 AM - 18:00 PM'), ('20:00 AM - 00:00 AM', '20:00 AM - 00:00 AM')], max_length=50, null=True),
        ),
    ]
